// ============================================================
// SwiftTray — Mock Data for Demo Mode
// ============================================================

import { Outlet, MenuItem, Order, Notification, Coupon, Review } from "@/types";

export const MOCK_OUTLETS: Outlet[] = [
  {
    _id: "outlet_1",
    name: "Spice Junction",
    slug: "spice-junction",
    description: "Authentic North Indian cuisine with a modern twist. Famous for our butter chicken and fresh naan bread.",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&h=400&fit=crop",
    location: "Main Canteen, Ground Floor",
    rating: 4.6,
    reviewCount: 342,
    isOpen: true,
    operatingHours: { open: "08:00", close: "21:00" },
    tags: ["North Indian", "Biryani", "Thali"],
    avgPrepTime: 12,
    _creationTime: Date.now() - 86400000 * 90,
  },
  {
    _id: "outlet_2",
    name: "Dragon Bowl",
    slug: "dragon-bowl",
    description: "Quick and delicious Chinese food. From crispy noodles to sizzling Manchurian, we've got your cravings covered.",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&h=300&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=1200&h=400&fit=crop",
    location: "Food Court, 1st Floor",
    rating: 4.3,
    reviewCount: 218,
    isOpen: true,
    operatingHours: { open: "09:00", close: "22:00" },
    tags: ["Chinese", "Fast Food", "Noodles"],
    avgPrepTime: 10,
    _creationTime: Date.now() - 86400000 * 85,
  },
  {
    _id: "outlet_3",
    name: "South Express",
    slug: "south-express",
    description: "Traditional South Indian breakfast and meals. Our dosas and idlis are made fresh with authentic flavors.",
    image: "https://images.unsplash.com/photo-1630383249896-424e482df921?w=400&h=300&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&h=400&fit=crop",
    location: "Hostel Block A, Ground Floor",
    rating: 4.8,
    reviewCount: 456,
    isOpen: true,
    operatingHours: { open: "07:00", close: "20:00" },
    tags: ["South Indian", "Breakfast", "Healthy"],
    avgPrepTime: 8,
    _creationTime: Date.now() - 86400000 * 100,
  },
  {
    _id: "outlet_4",
    name: "Brew & Bite",
    slug: "brew-and-bite",
    description: "Premium coffee, shakes, and light bites. The perfect spot for study sessions and quick energy boosts.",
    image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=400&h=300&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1200&h=400&fit=crop",
    location: "Library Building, Ground Floor",
    rating: 4.5,
    reviewCount: 189,
    isOpen: true,
    operatingHours: { open: "07:30", close: "23:00" },
    tags: ["Beverages", "Snacks", "Cafe"],
    avgPrepTime: 5,
    _creationTime: Date.now() - 86400000 * 70,
  },
  {
    _id: "outlet_5",
    name: "Green Leaf",
    slug: "green-leaf",
    description: "Healthy salads, wraps, smoothie bowls, and guilt-free meals. Fuel your body the right way!",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=1200&h=400&fit=crop",
    location: "Sports Complex, 1st Floor",
    rating: 4.4,
    reviewCount: 126,
    isOpen: true,
    operatingHours: { open: "08:00", close: "20:00" },
    tags: ["Healthy", "Salads", "Smoothies"],
    avgPrepTime: 7,
    _creationTime: Date.now() - 86400000 * 60,
  },
  {
    _id: "outlet_6",
    name: "Burger Barn",
    slug: "burger-barn",
    description: "Juicy burgers, loaded fries, and chunky shakes. Your go-to spot for the ultimate comfort food.",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1466220549276-aef9ce186540?w=1200&h=400&fit=crop",
    location: "Student Center, Ground Floor",
    rating: 4.2,
    reviewCount: 298,
    isOpen: false,
    operatingHours: { open: "10:00", close: "22:00" },
    tags: ["Fast Food", "Burgers", "American"],
    avgPrepTime: 15,
    _creationTime: Date.now() - 86400000 * 45,
  },
];

export const MOCK_MENU_ITEMS: MenuItem[] = [
  // Spice Junction
  {
    _id: "item_1",
    outletId: "outlet_1",
    name: "Butter Chicken",
    description: "Tender chicken in rich, creamy tomato gravy with aromatic spices. Served with choice of bread.",
    price: 180,
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400&h=300&fit=crop",
    category: "lunch",
    isAvailable: true,
    prepTime: 15,
    nutrition: { calories: 450, protein: "28g", carbs: "12g", fat: "32g", allergens: ["dairy", "gluten"] },
    customizations: [
      { name: "Spice Level", options: [{ label: "Mild", price: 0 }, { label: "Medium", price: 0 }, { label: "Hot", price: 0 }], required: true, maxSelect: 1 },
      { name: "Bread", options: [{ label: "Naan", price: 0 }, { label: "Butter Naan", price: 20 }, { label: "Garlic Naan", price: 30 }], required: false, maxSelect: 1 },
    ],
    tags: ["Bestseller", "Non-Veg"],
    orderCount: 1250,
    _creationTime: Date.now() - 86400000 * 80,
  },
  {
    _id: "item_2",
    outletId: "outlet_1",
    name: "Paneer Tikka",
    description: "Marinated cottage cheese cubes grilled to perfection with bell peppers and onions.",
    price: 150,
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400&h=300&fit=crop",
    category: "snacks",
    isAvailable: true,
    prepTime: 12,
    nutrition: { calories: 320, protein: "18g", carbs: "8g", fat: "24g", allergens: ["dairy"] },
    customizations: [
      { name: "Portion", options: [{ label: "Half", price: 0 }, { label: "Full", price: 80 }], required: true, maxSelect: 1 },
    ],
    tags: ["Popular", "Veg"],
    orderCount: 890,
    _creationTime: Date.now() - 86400000 * 78,
  },
  {
    _id: "item_3",
    outletId: "outlet_1",
    name: "Hyderabadi Biryani",
    description: "Fragrant basmati rice layered with spiced chicken, saffron, and fresh herbs. Served with raita.",
    price: 220,
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&h=300&fit=crop",
    category: "biryani",
    isAvailable: true,
    prepTime: 20,
    nutrition: { calories: 650, protein: "35g", carbs: "75g", fat: "22g" },
    customizations: [
      { name: "Type", options: [{ label: "Chicken", price: 0 }, { label: "Mutton", price: 60 }], required: true, maxSelect: 1 },
    ],
    tags: ["Bestseller", "Non-Veg"],
    orderCount: 1580,
    _creationTime: Date.now() - 86400000 * 75,
  },
  {
    _id: "item_4",
    outletId: "outlet_1",
    name: "Dal Makhani",
    description: "Slow-cooked black lentils in a rich buttery gravy. A comfort food classic.",
    price: 120,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
    category: "lunch",
    isAvailable: true,
    prepTime: 10,
    nutrition: { calories: 280, protein: "12g", carbs: "35g", fat: "12g" },
    customizations: [],
    tags: ["Veg", "Comfort Food"],
    orderCount: 670,
    _creationTime: Date.now() - 86400000 * 70,
  },
  // Dragon Bowl
  {
    _id: "item_5",
    outletId: "outlet_2",
    name: "Hakka Noodles",
    description: "Stir-fried noodles with fresh vegetables, soy sauce, and a hint of chili.",
    price: 120,
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&h=300&fit=crop",
    category: "chinese",
    isAvailable: true,
    prepTime: 10,
    nutrition: { calories: 380, protein: "8g", carbs: "55g", fat: "14g", allergens: ["gluten", "soy"] },
    customizations: [
      { name: "Type", options: [{ label: "Veg", price: 0 }, { label: "Chicken", price: 40 }, { label: "Egg", price: 20 }], required: true, maxSelect: 1 },
    ],
    tags: ["Popular", "Quick"],
    orderCount: 1100,
    _creationTime: Date.now() - 86400000 * 80,
  },
  {
    _id: "item_6",
    outletId: "outlet_2",
    name: "Manchurian",
    description: "Crispy vegetable balls tossed in spicy Indo-Chinese sauce. Irresistibly crunchy!",
    price: 100,
    image: "https://images.unsplash.com/photo-1645696301019-35adcc18fc94?w=400&h=300&fit=crop",
    category: "chinese",
    isAvailable: true,
    prepTime: 12,
    nutrition: { calories: 290, protein: "6g", carbs: "38g", fat: "14g" },
    customizations: [
      { name: "Style", options: [{ label: "Dry", price: 0 }, { label: "Gravy", price: 0 }], required: true, maxSelect: 1 },
    ],
    tags: ["Bestseller", "Veg"],
    orderCount: 920,
    _creationTime: Date.now() - 86400000 * 78,
  },
  {
    _id: "item_7",
    outletId: "outlet_2",
    name: "Fried Rice",
    description: "Aromatic rice wok-tossed with vegetables, egg, and savory seasonings.",
    price: 130,
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&h=300&fit=crop",
    category: "chinese",
    isAvailable: true,
    prepTime: 10,
    nutrition: { calories: 420, protein: "12g", carbs: "65g", fat: "14g" },
    customizations: [
      { name: "Type", options: [{ label: "Veg", price: 0 }, { label: "Chicken", price: 40 }, { label: "Egg", price: 20 }], required: true, maxSelect: 1 },
    ],
    tags: ["Quick"],
    orderCount: 780,
    _creationTime: Date.now() - 86400000 * 75,
  },
  // South Express
  {
    _id: "item_8",
    outletId: "outlet_3",
    name: "Masala Dosa",
    description: "Crispy golden dosa filled with spiced potato masala. Served with sambar and coconut chutney.",
    price: 70,
    image: "https://images.unsplash.com/photo-1668236543090-82eb5eace6d8?w=400&h=300&fit=crop",
    category: "south-indian",
    isAvailable: true,
    prepTime: 8,
    nutrition: { calories: 280, protein: "8g", carbs: "45g", fat: "8g" },
    customizations: [],
    tags: ["Bestseller", "Veg", "Breakfast"],
    orderCount: 2100,
    _creationTime: Date.now() - 86400000 * 90,
  },
  {
    _id: "item_9",
    outletId: "outlet_3",
    name: "Idli Sambar",
    description: "Fluffy steamed rice cakes with aromatic lentil soup and fresh chutneys.",
    price: 50,
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400&h=300&fit=crop",
    category: "south-indian",
    isAvailable: true,
    prepTime: 5,
    nutrition: { calories: 180, protein: "6g", carbs: "35g", fat: "2g" },
    customizations: [
      { name: "Quantity", options: [{ label: "2 pcs", price: 0 }, { label: "4 pcs", price: 40 }], required: true, maxSelect: 1 },
    ],
    tags: ["Healthy", "Veg", "Breakfast"],
    orderCount: 1800,
    _creationTime: Date.now() - 86400000 * 88,
  },
  {
    _id: "item_10",
    outletId: "outlet_3",
    name: "Filter Coffee",
    description: "Traditional South Indian filter coffee. Strong, aromatic, and soul-warming.",
    price: 30,
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=300&fit=crop",
    category: "beverages",
    isAvailable: true,
    prepTime: 3,
    nutrition: { calories: 80, protein: "2g", carbs: "8g", fat: "4g", allergens: ["dairy"] },
    customizations: [],
    tags: ["Quick", "Hot"],
    orderCount: 3200,
    _creationTime: Date.now() - 86400000 * 85,
  },
  // Brew & Bite
  {
    _id: "item_11",
    outletId: "outlet_4",
    name: "Cappuccino",
    description: "Rich espresso topped with velvety steamed milk foam. The classic pick-me-up.",
    price: 120,
    image: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400&h=300&fit=crop",
    category: "beverages",
    isAvailable: true,
    prepTime: 5,
    nutrition: { calories: 120, protein: "6g", carbs: "10g", fat: "6g", allergens: ["dairy"] },
    customizations: [
      { name: "Size", options: [{ label: "Regular", price: 0 }, { label: "Large", price: 40 }], required: true, maxSelect: 1 },
      { name: "Milk", options: [{ label: "Regular", price: 0 }, { label: "Oat Milk", price: 30 }, { label: "Almond Milk", price: 30 }], required: false, maxSelect: 1 },
    ],
    tags: ["Hot", "Popular"],
    orderCount: 1500,
    _creationTime: Date.now() - 86400000 * 65,
  },
  {
    _id: "item_12",
    outletId: "outlet_4",
    name: "Cold Brew",
    description: "Smooth, bold cold-brewed coffee steeped for 18 hours. Refreshingly intense.",
    price: 150,
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=300&fit=crop",
    category: "beverages",
    isAvailable: true,
    prepTime: 3,
    nutrition: { calories: 10, protein: "0g", carbs: "0g", fat: "0g" },
    customizations: [
      { name: "Size", options: [{ label: "Regular", price: 0 }, { label: "Large", price: 40 }], required: true, maxSelect: 1 },
    ],
    tags: ["Cold", "Popular"],
    orderCount: 980,
    _creationTime: Date.now() - 86400000 * 60,
  },
  {
    _id: "item_13",
    outletId: "outlet_4",
    name: "Chocolate Shake",
    description: "Thick, creamy chocolate milkshake topped with whipped cream and chocolate shavings.",
    price: 140,
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400&h=300&fit=crop",
    category: "beverages",
    isAvailable: true,
    prepTime: 5,
    nutrition: { calories: 380, protein: "10g", carbs: "52g", fat: "16g", allergens: ["dairy"] },
    customizations: [],
    tags: ["Cold", "Sweet"],
    orderCount: 720,
    _creationTime: Date.now() - 86400000 * 55,
  },
  // Green Leaf
  {
    _id: "item_14",
    outletId: "outlet_5",
    name: "Buddha Bowl",
    description: "Quinoa, avocado, roasted chickpeas, kale, and tahini dressing. Nutrient powerhouse!",
    price: 200,
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop",
    category: "healthy",
    isAvailable: true,
    prepTime: 8,
    nutrition: { calories: 380, protein: "15g", carbs: "42g", fat: "18g" },
    customizations: [
      { name: "Add Protein", options: [{ label: "None", price: 0 }, { label: "Grilled Chicken", price: 60 }, { label: "Tofu", price: 40 }], required: false, maxSelect: 1 },
    ],
    tags: ["Healthy", "Popular", "Veg"],
    orderCount: 450,
    _creationTime: Date.now() - 86400000 * 55,
  },
  {
    _id: "item_15",
    outletId: "outlet_5",
    name: "Berry Smoothie Bowl",
    description: "Blended acai and mixed berries topped with granola, banana, and chia seeds.",
    price: 180,
    image: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=400&h=300&fit=crop",
    category: "healthy",
    isAvailable: true,
    prepTime: 5,
    nutrition: { calories: 280, protein: "8g", carbs: "48g", fat: "6g" },
    customizations: [],
    tags: ["Breakfast", "Veg", "Popular"],
    orderCount: 380,
    _creationTime: Date.now() - 86400000 * 50,
  },
  // Burger Barn
  {
    _id: "item_16",
    outletId: "outlet_6",
    name: "Classic Smash Burger",
    description: "Double smashed beef patty with melted cheese, pickles, caramelized onions on a brioche bun.",
    price: 190,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop",
    category: "fast-food",
    isAvailable: true,
    prepTime: 15,
    nutrition: { calories: 650, protein: "35g", carbs: "42g", fat: "38g", allergens: ["gluten", "dairy"] },
    customizations: [
      { name: "Extras", options: [{ label: "Extra Cheese", price: 30 }, { label: "Bacon", price: 40 }, { label: "Jalapeños", price: 20 }], required: false, maxSelect: 3 },
    ],
    tags: ["Bestseller", "Non-Veg"],
    orderCount: 1300,
    _creationTime: Date.now() - 86400000 * 40,
  },
  {
    _id: "item_17",
    outletId: "outlet_6",
    name: "Loaded Fries",
    description: "Crispy golden fries loaded with cheese sauce, jalapenos, and sour cream.",
    price: 120,
    image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&h=300&fit=crop",
    category: "snacks",
    isAvailable: true,
    prepTime: 10,
    nutrition: { calories: 480, protein: "8g", carbs: "58g", fat: "26g" },
    customizations: [],
    tags: ["Popular", "Veg"],
    orderCount: 890,
    _creationTime: Date.now() - 86400000 * 38,
  },
  {
    _id: "item_18",
    outletId: "outlet_6",
    name: "Oreo Milkshake",
    description: "Crushed Oreo cookies blended with vanilla ice cream and topped with whipped cream.",
    price: 160,
    image: "https://images.unsplash.com/photo-1553787499-6f9133860278?w=400&h=300&fit=crop",
    category: "beverages",
    isAvailable: true,
    prepTime: 5,
    nutrition: { calories: 420, protein: "10g", carbs: "62g", fat: "16g", allergens: ["dairy", "gluten"] },
    customizations: [],
    tags: ["Sweet", "Cold"],
    orderCount: 560,
    _creationTime: Date.now() - 86400000 * 35,
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    _id: "order_1",
    userId: "user_1",
    outletId: "outlet_1",
    outletName: "Spice Junction",
    outletImage: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop",
    items: [
      { menuItemId: "item_1", name: "Butter Chicken", price: 180, quantity: 1, customizations: [{ name: "Spice Level", selected: "Medium", price: 0 }, { name: "Bread", selected: "Garlic Naan", price: 30 }] },
      { menuItemId: "item_3", name: "Hyderabadi Biryani", price: 220, quantity: 1, customizations: [{ name: "Type", selected: "Chicken", price: 0 }] },
    ],
    subtotal: 430,
    tax: 22,
    discount: 0,
    totalAmount: 452,
    status: "preparing",
    statusHistory: [
      { status: "placed", timestamp: Date.now() - 900000 },
      { status: "accepted", timestamp: Date.now() - 720000 },
      { status: "preparing", timestamp: Date.now() - 300000 },
    ],
    pickupSlot: "12:30",
    pickupToken: "ST-A7K2",
    notes: "Extra raita please",
    paymentStatus: "completed",
    estimatedReadyTime: Date.now() + 600000,
    _creationTime: Date.now() - 900000,
  },
  {
    _id: "order_2",
    userId: "user_1",
    outletId: "outlet_3",
    outletName: "South Express",
    outletImage: "https://images.unsplash.com/photo-1630383249896-424e482df921?w=400&h=300&fit=crop",
    items: [
      { menuItemId: "item_8", name: "Masala Dosa", price: 70, quantity: 2, customizations: [] },
      { menuItemId: "item_10", name: "Filter Coffee", price: 30, quantity: 2, customizations: [] },
    ],
    subtotal: 200,
    tax: 10,
    discount: 0,
    totalAmount: 210,
    status: "picked_up",
    statusHistory: [
      { status: "placed", timestamp: Date.now() - 7200000 },
      { status: "accepted", timestamp: Date.now() - 7100000 },
      { status: "preparing", timestamp: Date.now() - 6900000 },
      { status: "ready", timestamp: Date.now() - 6600000 },
      { status: "picked_up", timestamp: Date.now() - 6400000 },
    ],
    pickupSlot: "09:00",
    pickupToken: "ST-B3M9",
    paymentStatus: "completed",
    _creationTime: Date.now() - 7200000,
  },
  {
    _id: "order_3",
    userId: "user_1",
    outletId: "outlet_4",
    outletName: "Brew & Bite",
    outletImage: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=400&h=300&fit=crop",
    items: [
      { menuItemId: "item_11", name: "Cappuccino", price: 120, quantity: 1, customizations: [{ name: "Size", selected: "Large", price: 40 }] },
    ],
    subtotal: 160,
    tax: 8,
    discount: 0,
    totalAmount: 168,
    status: "ready",
    statusHistory: [
      { status: "placed", timestamp: Date.now() - 600000 },
      { status: "accepted", timestamp: Date.now() - 540000 },
      { status: "preparing", timestamp: Date.now() - 400000 },
      { status: "ready", timestamp: Date.now() - 120000 },
    ],
    pickupSlot: "13:00",
    pickupToken: "ST-C5P1",
    paymentStatus: "completed",
    estimatedReadyTime: Date.now() - 120000,
    _creationTime: Date.now() - 600000,
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    _id: "notif_1",
    userId: "user_1",
    type: "order_update",
    title: "Order Ready! 🎉",
    message: "Your Cappuccino from Brew & Bite is ready for pickup. Token: ST-C5P1",
    orderId: "order_3",
    isRead: false,
    _creationTime: Date.now() - 120000,
  },
  {
    _id: "notif_2",
    userId: "user_1",
    type: "order_update",
    title: "Preparing your order 👨‍🍳",
    message: "Spice Junction has started preparing your Butter Chicken and Biryani.",
    orderId: "order_1",
    isRead: false,
    _creationTime: Date.now() - 300000,
  },
  {
    _id: "notif_3",
    userId: "user_1",
    type: "promo",
    title: "20% OFF on Chinese! 🎊",
    message: "Use code DRAGON20 at Dragon Bowl. Valid today only!",
    isRead: true,
    _creationTime: Date.now() - 3600000,
  },
  {
    _id: "notif_4",
    userId: "user_1",
    type: "order_update",
    title: "Order Delivered ✅",
    message: "Your Masala Dosa order from South Express was picked up. Enjoy!",
    orderId: "order_2",
    isRead: true,
    _creationTime: Date.now() - 6400000,
  },
];

export const MOCK_COUPONS: Coupon[] = [
  {
    _id: "coupon_1",
    code: "WELCOME50",
    discountType: "percentage",
    discountValue: 50,
    minOrder: 100,
    maxDiscount: 100,
    validUntil: Date.now() + 86400000 * 30,
    usageLimit: 1,
    usedCount: 0,
    isActive: true,
    _creationTime: Date.now() - 86400000,
  },
  {
    _id: "coupon_2",
    code: "DRAGON20",
    discountType: "percentage",
    discountValue: 20,
    minOrder: 150,
    maxDiscount: 60,
    validUntil: Date.now() + 86400000,
    usageLimit: 100,
    usedCount: 42,
    outletId: "outlet_2",
    isActive: true,
    _creationTime: Date.now() - 86400000 * 2,
  },
  {
    _id: "coupon_3",
    code: "FLAT30",
    discountType: "flat",
    discountValue: 30,
    minOrder: 200,
    maxDiscount: 30,
    validUntil: Date.now() + 86400000 * 7,
    usageLimit: 500,
    usedCount: 123,
    isActive: true,
    _creationTime: Date.now() - 86400000 * 5,
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    _id: "review_1",
    userId: "user_1",
    userName: "Arjun M.",
    outletId: "outlet_1",
    orderId: "order_2",
    rating: 5,
    comment: "Best biryani on campus! Always consistent quality.",
    _creationTime: Date.now() - 86400000 * 3,
  },
  {
    _id: "review_2",
    userId: "user_2",
    userName: "Priya S.",
    outletId: "outlet_3",
    orderId: "order_3",
    rating: 5,
    comment: "The dosas are amazing! Authentic taste and quick service.",
    _creationTime: Date.now() - 86400000 * 5,
  },
];

// Helper functions to work with mock data
export function getOutletBySlug(slug: string): Outlet | undefined {
  return MOCK_OUTLETS.find(o => o.slug === slug);
}

export function getMenuItemsByOutlet(outletId: string): MenuItem[] {
  return MOCK_MENU_ITEMS.filter(item => item.outletId === outletId);
}

export function getMenuItemById(id: string): MenuItem | undefined {
  return MOCK_MENU_ITEMS.find(item => item._id === id);
}

export function getTrendingItems(limit: number = 6): MenuItem[] {
  return [...MOCK_MENU_ITEMS]
    .filter(item => item.isAvailable)
    .sort((a, b) => b.orderCount - a.orderCount)
    .slice(0, limit);
}

export function searchMenuItems(query: string): MenuItem[] {
  const q = query.toLowerCase();
  return MOCK_MENU_ITEMS.filter(
    item =>
      item.name.toLowerCase().includes(q) ||
      item.description.toLowerCase().includes(q) ||
      item.tags.some(t => t.toLowerCase().includes(q)) ||
      item.category.toLowerCase().includes(q)
  );
}

export function getOutletById(id: string): Outlet | undefined {
  return MOCK_OUTLETS.find(o => o._id === id);
}
