"use client";

import Link from "next/link";
import Image from "next/image";
import { useQuery } from "convex/react";
import { ArrowRight, Bell, Clock, GraduationCap, History, MapPin, Star, TrendingUp, Zap } from "lucide-react";
import { api } from "@convex/_generated/api";
import { formatPrice, formatRelativeTime, getGreeting, getOrderStatusColor, getOrderStatusLabel } from "@/lib/utils";

export default function StudentDashboardPage() {
  const account = useQuery(api.users.current, {});
  const activeOrders = useQuery(api.orders.getActiveOrders, {});
  const orders = useQuery(api.orders.getMyOrders, {});
  const notifications = useQuery(api.notifications.getForUser, {});
  const outlets = useQuery(api.outlets.list, { openOnly: true });
  const trending = useQuery(api.menuItems.getTrending, { limit: 6 });
  const unread = (notifications ?? []).find((notification) => !notification.isRead);
  const outletById = new Map((outlets ?? []).map((outlet) => [String(outlet._id), outlet]));
  return <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8 pb-10">
    <header className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><div className="flex items-center gap-2 mb-1"><div className="neu-icon-mint w-8 h-8 rounded-lg"><GraduationCap className="w-4 h-4"/></div><span className="text-xs font-semibold text-primary uppercase tracking-wider">Student portal</span></div><h1 className="text-2xl md:text-3xl font-extrabold">{getGreeting()}, <span className="gradient-text">{account?.profile?.name?.split(" ")[0] ?? "Student"}</span></h1><p className="text-sm text-muted-foreground">Browse live outlets and track your real orders.</p></div><Link href="/outlets" className="min-h-11 px-4 rounded-xl neu-btn-primary font-bold flex items-center justify-center gap-2">Browse outlets <ArrowRight className="w-4 h-4"/></Link></header>
    {activeOrders && activeOrders.length > 0 && <Link href={`/orders/${activeOrders[0]._id}`} className="neu-card-static p-4 border-2 border-primary/30 flex items-center gap-4"><div className="neu-icon-mint w-12 h-12 rounded-xl"><Zap className="w-6 h-6"/></div><div className="flex-1"><p className="font-bold">Active order · {activeOrders[0].outletName}</p><p className="text-xs text-muted-foreground">{activeOrders[0].paymentStatus === "completed" ? `${activeOrders[0].items.length} items` : "Payment still required"}</p></div><span className={`px-3 py-1 rounded-full text-xs border ${getOrderStatusColor(activeOrders[0].status)}`}>{getOrderStatusLabel(activeOrders[0].status)}</span></Link>}
    {unread && <div className="neu-card-static p-4 flex items-center gap-3 border-l-4 border-primary"><Bell className="w-5 h-5 text-primary"/><div className="flex-1 min-w-0"><p className="font-semibold text-sm truncate">{unread.title}</p><p className="text-xs text-muted-foreground truncate">{unread.message}</p></div><time className="text-xs text-muted-foreground">{formatRelativeTime(unread._creationTime)}</time></div>}
    <section><div className="flex items-center justify-between mb-4"><h2 className="text-lg font-bold flex items-center gap-2"><MapPin className="w-5 h-5 text-primary"/>Open outlets</h2><Link href="/outlets" className="text-sm text-primary font-semibold">View all</Link></div>{outlets === undefined ? <p className="py-10 text-center text-sm text-muted-foreground">Loading outlets…</p> : outlets.length === 0 ? <p className="py-10 text-center text-sm text-muted-foreground">No outlets are open right now.</p> : <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">{outlets.slice(0,4).map((outlet) => <Link key={outlet._id} href={`/outlets/${outlet.slug}`} className="neu-card overflow-hidden group"><div className="relative h-28"><Image src={outlet.image} alt={outlet.name} fill sizes="(max-width: 640px) 50vw, 25vw" className="object-cover"/></div><div className="p-3"><h3 className="font-bold truncate">{outlet.name}</h3><p className="text-xs text-muted-foreground flex gap-3"><span className="flex items-center gap-1"><Star className="w-3 h-3"/>{outlet.rating}</span><span className="flex items-center gap-1"><Clock className="w-3 h-3"/>{outlet.avgPrepTime} min</span></p></div></Link>)}</div>}</section>
    <section><h2 className="text-lg font-bold flex items-center gap-2 mb-4"><TrendingUp className="w-5 h-5 text-primary"/>Trending menu items</h2>{trending === undefined ? <p className="py-10 text-center text-sm text-muted-foreground">Loading menu…</p> : trending.length === 0 ? <p className="py-10 text-center text-sm text-muted-foreground">No menu activity yet.</p> : <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{trending.map((item) => { const outlet = outletById.get(String(item.outletId)); return <Link key={item._id} href={outlet ? `/outlets/${outlet.slug}` : "/outlets"} className="neu-card p-3 flex gap-3"><div className="relative w-20 h-20 rounded-xl overflow-hidden"><Image src={item.image} alt={item.name} fill sizes="80px" className="object-cover"/></div><div className="flex-1 min-w-0"><h3 className="font-bold truncate">{item.name}</h3><p className="text-xs text-muted-foreground truncate">{outlet?.name ?? "Campus outlet"}</p><p className="font-bold gradient-text mt-3">{formatPrice(item.price)}</p></div></Link>; })}</div>}</section>
    <section><div className="flex items-center justify-between mb-4"><h2 className="text-lg font-bold flex items-center gap-2"><History className="w-5 h-5 text-primary"/>Recent orders</h2><Link href="/orders" className="text-sm text-primary font-semibold">View all</Link></div>{orders === undefined ? <p className="py-10 text-center text-sm text-muted-foreground">Loading orders…</p> : orders.length === 0 ? <p className="py-10 text-center text-sm text-muted-foreground">Your first order will appear here.</p> : <div className="space-y-3">{orders.slice(0,3).map((order) => <Link href={`/orders/${order._id}`} key={order._id} className="neu-card p-4 flex items-center gap-4"><div className="relative w-12 h-12 rounded-xl overflow-hidden"><Image src={order.outletImage} alt="" fill sizes="48px" className="object-cover"/></div><div className="flex-1 min-w-0"><p className="font-bold truncate">{order.outletName}</p><p className="text-xs text-muted-foreground">{formatRelativeTime(order._creationTime)}</p></div><div className="text-right"><p className="font-bold">{formatPrice(order.totalAmount)}</p><span className={`text-[10px] ${getOrderStatusColor(order.status)}`}>{getOrderStatusLabel(order.status)}</span></div></Link>)}</div>}</section>
  </div>;
}
