"use client";

import { FormEvent, useState } from "react";
import { useMutation, useQuery } from "convex/react";
import { Plus, Power, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { api } from "@convex/_generated/api";
import { formatPrice } from "@/lib/utils";

export default function AdminCouponsPage() {
  const coupons = useQuery(api.coupons.list, {});
  const create = useMutation(api.coupons.create);
  const setActive = useMutation(api.coupons.setActive);
  const remove = useMutation(api.coupons.remove);
  const [open, setOpen] = useState(false);
  const [pending, setPending] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setPending(true); try { await create({ code: String(form.get("code")), discountType: form.get("discountType") === "flat" ? "flat" : "percentage", discountValue: Number(form.get("discountValue")), minOrder: Number(form.get("minOrder")), maxDiscount: Number(form.get("maxDiscount")), usageLimit: Number(form.get("usageLimit")), validUntil: new Date(`${form.get("validUntil")}T23:59:59`).getTime() }); event.currentTarget.reset(); setOpen(false); toast.success("Coupon created"); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not create coupon"); } finally { setPending(false); } };
  return <div className="space-y-6"><header className="flex justify-between gap-4"><div><h1 className="text-2xl font-extrabold">Coupon <span className="gradient-text">Management</span></h1><p className="text-sm text-muted-foreground">{coupons?.length ?? 0} live database records</p></div><button type="button" onClick={() => setOpen((value) => !value)} className="min-h-11 px-4 rounded-xl gradient-primary text-white text-sm font-semibold flex items-center gap-2"><Plus className="w-4 h-4"/>Create</button></header>
  {open && <form onSubmit={submit} className="glass-card p-5 grid sm:grid-cols-3 gap-4">{[["Code","code","text"],["Discount value","discountValue","number"],["Minimum order","minOrder","number"],["Maximum discount","maxDiscount","number"],["Usage limit","usageLimit","number"],["Valid until","validUntil","date"]].map(([label,name,type]) => <label key={name} className="text-sm font-semibold">{label}<input name={name} type={type} required min={type === "number" ? "0" : undefined} className="mt-2 w-full min-h-11 px-3 rounded-xl bg-secondary/50 border"/></label>)}<label className="text-sm font-semibold">Discount type<select name="discountType" className="mt-2 w-full min-h-11 px-3 rounded-xl bg-secondary/50 border"><option value="percentage">Percentage</option><option value="flat">Flat amount</option></select></label><button disabled={pending} className="sm:col-span-2 min-h-11 self-end rounded-xl gradient-primary text-white font-semibold disabled:opacity-60">{pending ? "Creating…" : "Create coupon"}</button></form>}
  <div className="glass-card overflow-x-auto"><div className="min-w-[720px]"><div className="grid grid-cols-12 gap-3 px-4 py-3 text-xs font-semibold text-muted-foreground border-b"><span className="col-span-2">Code</span><span className="col-span-2">Discount</span><span className="col-span-2">Minimum</span><span className="col-span-2 text-center">Usage</span><span className="col-span-2">Expires</span><span className="col-span-2 text-right">Actions</span></div>{coupons === undefined ? <p className="p-10 text-center text-sm text-muted-foreground">Loading coupons…</p> : coupons.length === 0 ? <p className="p-10 text-center text-sm text-muted-foreground">No coupons configured.</p> : coupons.map((coupon) => <div key={coupon._id} className={`grid grid-cols-12 gap-3 px-4 py-3 items-center border-b last:border-0 ${coupon.isActive ? "" : "opacity-60"}`}><span className="col-span-2 font-mono font-bold text-xs">{coupon.code}</span><span className="col-span-2 text-xs">{coupon.discountType === "percentage" ? `${coupon.discountValue}%` : formatPrice(coupon.discountValue)}</span><span className="col-span-2 text-xs">{formatPrice(coupon.minOrder)}</span><span className="col-span-2 text-center text-xs">{coupon.usedCount}/{coupon.usageLimit}</span><span className="col-span-2 text-xs">{new Date(coupon.validUntil).toLocaleDateString()}</span><div className="col-span-2 flex justify-end gap-2"><button type="button" onClick={() => setActive({ id: coupon._id, isActive: !coupon.isActive }).catch(() => toast.error("Could not update coupon"))} className="min-w-10 min-h-10 rounded-xl bg-secondary flex items-center justify-center" aria-label={coupon.isActive ? "Deactivate coupon" : "Activate coupon"}><Power className="w-4 h-4"/></button><button type="button" onClick={() => window.confirm("Delete unused coupon?") && remove({ id: coupon._id }).catch((error) => toast.error(error instanceof Error ? error.message : "Could not delete coupon"))} className="min-w-10 min-h-10 rounded-xl bg-red-500/10 text-red-600 flex items-center justify-center" aria-label="Delete coupon"><Trash2 className="w-4 h-4"/></button></div></div>)}</div></div></div>;
}
